djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from leads.views import LandingPageView, SignupView

urlpatterns = [
    path("", LandingPageView.as_view(), name="landing-page"),
    path('admin/', admin.site.urls),
    path("leads/", include('leads.urls', namespace="leads")),
    path("agents/", include('agents.urls'), name=""),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
import leads.views as lead_views

app_name = "leads"

urlpatterns = [
    path("", lead_views.LeadListView.as_view(), name='lead-list'),
    path("create/", lead_views.LeadCreateView.as_view(), name='lead-create'),
    path("<pk>/", lead_views.LeadDetailView.as_view(), name='lead-detail'),
    path("<pk>/update/", lead_views.LeadUpdateView.as_view(), name='lead-update'),
    path("<pk>/delete/", lead_views.LeadDeleteView.as_view(), name='lead-delete'),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser): # inheriting fields lile first_name, last_name, email, is_staff..
    is_organizer = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username
    

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE) 
    
    def __str__(self):
        return self.user.username
    
class Lead(models.Model):
    
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey("Agent", on_delete=models.CASCADE, null=True, default=1)
    
    def __str__(self):
        return self.first_name
    

def post_user_created_signal(sender, instance, created, **kwargs):
   if created:
       UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)
    
    

leads/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Lead, User

import ast

class LeadModelForm(forms.ModelForm):
    class Meta: # specifiy some information about the model
        model = Lead
        fields = (
            "first_name",
            "last_name",
            "age",
            "agent",
        )



class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)
    
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {"username" : UsernameField}

leads/views.py
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.views import generic
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Lead, Agent
from .forms import LeadForm, LeadModelForm, CustomUserCreationForm
from agents.mixins import OrganizerAndLoginRequiredMixing

# CRUD -> Create, Retrieve, Update , Delete + List

# Class Based Views

class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm
    
    def get_success_url(self):
        return reverse("leads:lead-list")

class LandingPageView(generic.TemplateView):
    template_name = "landing_page.html"

class LeadListView(LoginRequiredMixin, generic.ListView):
    template_name = "leads/lead_list.html"
    queryset = Lead.objects.all()
    context_object_name = "leads"
    
class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/lead_detail.html"
    queryset = Lead.objects.all()
    context_object_name = "lead"
    
class LeadCreateView(OrganizerAndLoginRequiredMixing, generic.CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm
    
    def get_success_url(self):
        return reverse("leads:lead-list")
    
    def form_valid(self, form):
        # TODO send email 
        send_mail (
            subject = "A lead has been created",
            message = "Go to the site to see the new lead",
            from_email = "test@test.com",
            recipient_list = [ "test2@test.com"]
        )
        
        return super(LeadCreateView, self).form_valid(form)

class LeadUpdateView(OrganizerAndLoginRequiredMixing, generic.UpdateView):
    form_class = LeadModelForm
    queryset = Lead.objects.all()
    template_name = "leads/lead_update.html"
    
    def get_success_url(self):
        return reverse("leads:lead-detail", kwargs={"pk": self.object.pk})

class LeadDeleteView(OrganizerAndLoginRequiredMixing, generic.DeleteView):
    model = Lead
    template_name = "leads/lead_delete.html"
    
    def get_success_url(self):
        return reverse("leads:lead-list")
    


# # function baseed views
# def landing_page(request):
#     return render(request, "landing_page.html")

# def lead_list(request):
#     leads = Lead.objects.all()
#     context = {
#         "leads": leads
#     }
#     return render(request, 'leads/lead_list.html', context)

# # def lead_detail(request,pk):
# #     lead = Lead.objects.get(id=pk)
# #     context = {
# #         "lead" : lead
# #     }
# #     return render(request, 'leads/lead_detail.html', context = context)

# def lead_create(request):
#     form = LeadModelForm()
#     print(request.POST)
#     if request.method == "POST":
#         form = LeadModelForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect("/leads")
#     context = {
#         "form" : form,
#     }
#     return render(request, "leads/lead_create.html", context)

# def lead_update(request, pk):
#     lead = Lead.objects.get(id=pk)
#     form = LeadModelForm(instance=lead) # populates the form with lead values
#     if request.method == "POST":
#         form = LeadModelForm(request.POST, instance=lead)
#         if form.is_valid():
#             form.save()
#             return redirect(f"/leads/{pk}/")
#     context = {
#         "lead" : lead,
#         "form" : form
#     }
#     return render(request, "leads/lead_update.html", context)
# def lead_delete(request,pk):
#     lead = Lead.objects.get(id=pk)
#     lead.delete()
#     return redirect("/leads")
    

    
# def lead_create(request):
#     form = LeadForm()
#     print(request.POST)
#     if request.method == "POST":
#         form = LeadForm(request.POST)
#         if form.is_valid():
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             agent = Agent.objects.first()
#             Lead.objects.create(
#                 first_name = first_name,
#                 last_name = last_name,
#                 age = age,
#                 agent = agent,
#             )
#             return redirect("/leads")
#     context = {
#         "form" : form,
#     }
#     return render(request, "leads/lead_create.html", context)

templates/leads/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>welcome</title>  
</head>
<body>
    <h1>welcome!</h1>
</body>
</html>

templates/leads/lead_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create a new Lead</title>
</head>
<body>
    <h1>
        <h1>Create a new Lead</h1>
        <form method="POST" action=".">
            {% csrf_token %}
            {{  form.as_p }}

            <button>Submit</button>
        </form>
    </h1>
</body>
</html>

templates/leads/lead_delete.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url "leads:lead-list" %}">Delete</a>
    <hr>
    <h1>Are you  sure you want to delete this lead ? </h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="flex text-white bg-red-200 border-0  my-3 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">
           Delete
        </button>
    </form>

{% endblock content %}

templates/leads/lead_detail.html
{% extends "base.html" %}

{% block content %}

        <a href="{% url "leads:lead-list" %}">back to leads</a> <hr>

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{lead.first_name}} </h1>
          <div class="flex mb-4">
            <a href="{% url "leads:lead-detail" lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
            <a href="{% url 'leads:lead-update' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Details</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900"> {{lead.age}} </span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Location</span>
            <span class="ml-auto text-gray-900"> Dummy Location </span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Cell Phone</span>
            <span class="ml-auto text-gray-900">+20685893903</span>
          </div>
          <div class="flex">
            <button class="flex ml-auto text-white bg-red-200 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">
              <a href="{% url "leads:lead-delete" lead.pk %}">Delete</a>
            </button>
            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
              </svg>
            </button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>

        {% comment %} <hr><a href="/leads/{{lead.id}}/update/">Update Lead</a> {% endcomment %}
        

{% endblock content %}

templates/leads/lead_list.html
{% extends "base.html" %}

{% block content %}

    
<section class="text-gray-400 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
  <div class="w-full py-6 mb-6 flex justify-between items-enter border-b border-gray-200">
      <div>
          <h1 class="text-4xl text-gray-800">Leads</h1>
      </div>
    {% if request.user.is_organizer %}
        <div class=" flex items-center text-gray-500 hover:text-blue-500">
            <a href="{% url "leads:lead-create" %}">Create a new Lead</a>
        </div>
    {% endif %}
  </div>
  <div class="flex flex-wrap -m-4">
      {% for lead in leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
          <div class="flex border-2 rounded-lg border-gray-300 p-8 sm:flex-row flex-col">
              <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-gray-300 text-indigo-400 flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                  <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
              </div>
              <div class="flex-grow">
              <h2 class="text-black text-lg title-font font-medium mb-3"> {{lead.first_name}} </h2>
              <p class="leading-relaxed text-base">Email :  {{lead.email}} </p>
              <a href="{% url "leads:lead-detail" lead.pk %}" class="mt-3 text-indigo-400 inline-flex items-center"> Details
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                  </svg>
              </a>
              </div>
          </div>
          </div>
      {% endfor %}
  </div>
  </div>
</section>

{% endblock content %}

templates/leads/lead_update.html
{% extends "base.html" %}
{% block content %}

        <a href="{% url "leads:lead-list" %}">back to leads</a> <hr>

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex ">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{lead.first_name}} </h1>
          <div class="flex mb-4">
            <a href="{% url "leads:lead-detail" lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
            <a href="{% url 'leads:lead-update' lead.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update Details</a>
          </div>
            <form method="POST" action=".">
                {% csrf_token %}
                {{  form.as_p }}
        
                <button>Submit</button>
            </form>
          </div>
          <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
        </div>
      </div>
    </div>
  </section>

      
{% endblock content %}