agents/urls.py
from django.urls import path
from agents.views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateViews, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path("", AgentListView.as_view(), name="agents-list"),
    path("agent-create/",AgentCreateView.as_view(), name="agent-create"),
    path("<int:pk>/",AgentDetailView.as_view(), name="agent-detail"),
    path("<int:pk>/update/",AgentUpdateViews.as_view(), name="agent-update"),
    path("<int:pk>/delete/", AgentDeleteView.as_view(), name="agent-delete"),
]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from leads.views import LandingPageView, SignupView

urlpatterns = [
    path("", LandingPageView.as_view(), name="landing-page"),
    path('admin/', admin.site.urls),
    path("leads/", include('leads.urls', namespace="leads")),
    path("agents/", include('agents.urls'), name=""),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
import leads.views as lead_views

app_name = "leads"

urlpatterns = [
    path("", lead_views.LeadListView.as_view(), name='lead-list'),
    path("create/", lead_views.LeadCreateView.as_view(), name='lead-create'),
    path("<pk>/", lead_views.LeadDetailView.as_view(), name='lead-detail'),
    path("<pk>/update/", lead_views.LeadUpdateView.as_view(), name='lead-update'),
    path("<pk>/delete/", lead_views.LeadDeleteView.as_view(), name='lead-delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <title>DJCRM</title>

</head>
<body class="bg-gray-200">
    <div class="max-w-6xl mx-auto ">
        {% include "navbar.html" %}
        {% block content %}
    
        {% endblock content %}
    </div>
</body>
</html>

templates/landing_page.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-400 bg-gray-900 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">CRM built with django</h1>
        <p class="leading-relaxed mb-8">Meggings kinfolk echo park stumptown DIY, kale chips beard jianbing tousled. Chambray dreamcatcher trust fund, kitsch vice godard disrupt ramps hexagon mustache umami snackwave tilde chillwave ugh. Pour-over meditation PBR&amp;B pickled ennui celiac mlkshk freegan photo booth af fingerstache pitchfork.</p>
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
          <button class="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-900  body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-white mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">DJCRM</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
          {% if request.user.is_authenticated %}
          {% if request.user.is_organizer %} 
            <a href="{% url "agents:agents-list" %}" class="mr-5 hover:text-blue-700">Agents</a>
          {% endif %}
          <a href="{% url "leads:lead-list" %}" class="mr-5 hover:text-blue-700">Leads</a>
              <p>Logged in as : {{request.user.username}} </p> 
              <a href="{% url "logout" %}" class="inline-flex items-center focus:outline-none ml-3 hover:text-red-700 rounded text-base mt-4 md:mt-0">
                Logout
              </a>
           {% else %}
           <a  href="{% url "signup" %}" class="mr-5 hover:text-blue-700">Sign Up</a>
           <a href="{% url "login" %}" class="inline-flex items-center focus:outline-none hover:text-blue-700 rounded text-base mt-4 md:mt-0">
             Login
           </a>
          {% endif %}
      </nav>

    </div>
  </header>